AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Sends log data from S3 to New Relic Logging.
Parameters:
  NRLicenseKey:
    Type: String
    Description: Your New Relic license key. Required to send logs to New Relic Logging.
    Default: "YOUR_LICENSE_KEY"
  NRLogType:
    Type: String
    Description: Your New Relic logtype. You may omit it when deploying the function.
    Default: ""

Metadata:
  AWS::ServerlessRepo::Application:
    Name: NewRelic-log-ingestion-s3
    Description: Send log data from a S3 bucket to New Relic Logging.
    Author: New Relic
    SpdxLicenseId: Apache-2.0
    LicenseUrl: LICENSE
    ReadmeUrl: README.md
    Labels: ['newrelic', 'logs', 'logging', 'ingestion', 'lambda', 's3']
    HomePageUrl: https://github.com/newrelic/aws_s3_log_ingestion_lambda
    SemanticVersion: 1.0.3
    SourceCodeUrl: https://github.com/newrelic/aws_s3_log_ingestion_lambda

Resources:
  NewRelicLogIngestionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Runtime: python3.7
      CodeUri: src/
      Handler: handler.lambda_handler
      FunctionName: NewRelic-s3-log-ingestion
      Timeout: 30
      Environment:
        Variables: 
          LICENSE_KEY: !Ref NRLicenseKey
          LOG_TYPE: !Ref NRLogType
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - 's3:GetObject'
              Resource: 'arn:aws:s3:::*'
      Events:
        BucketEvent1:
          Type: S3
          Properties:
            Bucket:
              Ref: SourceLogBucket
            Events:
              - 's3:ObjectCreated:*'

  SourceLogBucket:
    Type: 'AWS::S3::Bucket'